# Generated by Django 3.1.2 on 2021-01-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='groundId',
            new_name='groupId',
        ),
    ]
